### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by frankopkusianwar** [frankopkusianwar/enumerable_methods#2]

**Comment by mariosknl** [comment]
Try to test your methods with test cases from the website I gave you. A good idea is to make the check in the beginning before you get inside the if statement. Good approach though

**Comment by ghost** [comment]
Also, check the reviews from other people to help you figure out what you need. Use this[ link](https://github.com/blackpintz/Advanced-Building-Blocks---Enumerables/pull/2) to access my reviews. Good luck.
